version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin 816069153470.dkr.ecr.ap-south-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t python-app:latest .
      - docker tag python-app:latest 816069153470.dkr.ecr.ap-south-2.amazonaws.com/python-app:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 81606915347.dkr.ecr.ap-south-2.amazonaws.com/python-app:latest
